package ca.mcgill.ecse321.gallerysystem.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.fail;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.lenient;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.invocation.InvocationOnMock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.stubbing.Answer;

import ca.mcgill.ecse321.gallerysystem.dao.ArtPieceRepository;
import ca.mcgill.ecse321.gallerysystem.dao.ArtistRepository;
import ca.mcgill.ecse321.gallerysystem.dao.UserRepository;
import ca.mcgill.ecse321.gallerysystem.exception.ResourceNotFoundException;
import ca.mcgill.ecse321.gallerysystem.model.ArtPiece;
import ca.mcgill.ecse321.gallerysystem.model.Artist;
import ca.mcgill.ecse321.gallerysystem.model.User;

@ExtendWith(MockitoExtension.class)
public class TestCreateArtPiece {
	@Mock
	private ArtistRepository artistDao;
	@Mock
	private ArtPieceRepository artPieceDao;
	@Mock
	private UserRepository userDao;

	@InjectMocks
	private GallerySystemService service;

	// The one email the mocked ArtistRepository will recognize as a real, existing
	// artist
	private static final String VALID_ARTIST_EMAIL = "john@mail.com";

	@BeforeEach
	public void setMockOutput() {
		lenient().when(artistDao.findArtistByEmail(anyString())).thenAnswer((InvocationOnMock invocation) -> {
			String requestedEmail = invocation.getArgument(0);
			if (requestedEmail != null && requestedEmail.equals(VALID_ARTIST_EMAIL)) {
				Artist artist = new Artist();
				artist.setEmail(VALID_ARTIST_EMAIL);
				artist.setUserName("John");
				artist.setPassword("pass");
				return artist;
			}
			return null;
		});
		// Whenever anything is saved, just return the parameter object
		Answer<?> returnParameterAsAnswer = (InvocationOnMock invocation) -> {
			return invocation.getArgument(0);
		};
		lenient().when(artistDao.save(any(Artist.class))).thenAnswer(returnParameterAsAnswer);
		lenient().when(artPieceDao.save(any(ArtPiece.class))).thenAnswer(returnParameterAsAnswer);
		lenient().when(userDao.save(any(User.class))).thenAnswer(returnParameterAsAnswer);
	}

	/**
	 * Test to create an art piece with valid information, correctly associated with
	 * an
	 * existing artist. Note: artID is auto-generated by the database
	 * (@GeneratedValue),
	 * so it is not passed in and is expected to be null on the returned in-memory
	 * object
	 * (a real DB would assign it on insert).
	 */
	@Test
	public void testCreateArtPiece() {
		assertEquals(0, service.getAllArtPieces().size());

		String artName = "Riverside Tree";
		Integer quantity = 3;
		float price = 800;
		Integer discountPercentage = 10;
		Float commission = (float) 23.0;
		String description = "tree on a riverside";

		ArtPiece artPiece = null;
		try {
			artPiece = service.createArtPiece(artName, quantity, price, discountPercentage, commission, description,
					VALID_ARTIST_EMAIL);
		} catch (IllegalArgumentException e) {
			fail();
		}
		checkResultCreateArtPiece(artPiece, artName, quantity, price, discountPercentage, commission, description);
	}

	/**
	 * Verify the result of creating an art piece with the following parameters.
	 */
	private void checkResultCreateArtPiece(ArtPiece artPiece, String artName, Integer quantity, float price,
			Integer discountPercentage, Float commissionPercentage, String description) {
		assertNotNull(artPiece);
		assertEquals(artName, artPiece.getArtName());
		assertEquals(quantity, artPiece.getQuantity());
		assertEquals(discountPercentage, artPiece.getDiscountPercentage());
		assertEquals(description, artPiece.getDescription());
		assertEquals(VALID_ARTIST_EMAIL, artPiece.getArtist().getEmail());
		assertEquals((float) commissionPercentage, artPiece.getCommissionPercentage());
	}

	/**
	 * Test to create an art piece with a negative quantity. Should be rejected with
	 * a
	 * specific, quantity-related error message.
	 */
	@Test
	public void testCreateArtPieceNegativeQuantity() {
		String error = null;
		ArtPiece artPiece = null;
		try {
			artPiece = service.createArtPiece("Riverside Tree", -7, 800f, 10, 23f, "tree on a riverside",
					VALID_ARTIST_EMAIL);
		} catch (IllegalArgumentException e) {
			error = e.getMessage();
		}
		assertNull(artPiece);
		assertEquals("Quantity must be a positive number.", error);
	}

	/**
	 * Test to create an art piece with a negative price. Should be rejected with a
	 * specific, price-related error message.
	 */
	@Test
	public void testCreateArtPieceNegativePrice() {
		String error = null;
		ArtPiece artPiece = null;
		try {
			artPiece = service.createArtPiece("Riverside Tree", 3, -1f, 10, 23f, "tree on a riverside",
					VALID_ARTIST_EMAIL);
		} catch (IllegalArgumentException e) {
			error = e.getMessage();
		}
		assertNull(artPiece);
		assertEquals("Price cannot be negative.", error);
	}

	/**
	 * Test to create an art piece with a negative discount percentage. Should be
	 * rejected with a specific, discount-related error message.
	 */
	@Test
	public void testCreateArtPieceNegativeDiscount() {
		String error = null;
		ArtPiece artPiece = null;
		try {
			artPiece = service.createArtPiece("Riverside Tree", 3, 800f, -5, 23f, "tree on a riverside",
					VALID_ARTIST_EMAIL);
		} catch (IllegalArgumentException e) {
			error = e.getMessage();
		}
		assertNull(artPiece);
		assertEquals("Discount percentage cannot be null or negative.", error);
	}

	/**
	 * Test to create an art piece with a negative commission percentage. Should be
	 * rejected with a specific, commission-related error message.
	 */
	@Test
	public void testCreateArtPieceNegativeCommission() {
		String error = null;
		ArtPiece artPiece = null;
		try {
			artPiece = service.createArtPiece("Riverside Tree", 3, 800f, 10, -1f, "tree on a riverside",
					VALID_ARTIST_EMAIL);
		} catch (IllegalArgumentException e) {
			error = e.getMessage();
		}
		assertNull(artPiece);
		assertEquals("Commission percentage cannot be null or negative.", error);
	}

	/**
	 * Test to create an art piece with a blank name. Should be rejected -
	 * regression
	 * test for the old null-only check that let whitespace-only strings through.
	 */
	@Test
	public void testCreateArtPieceBlankName() {
		String error = null;
		ArtPiece artPiece = null;
		try {
			artPiece = service.createArtPiece("   ", 3, 800f, 10, 23f, "tree on a riverside", VALID_ARTIST_EMAIL);
		} catch (IllegalArgumentException e) {
			error = e.getMessage();
		}
		assertNull(artPiece);
		assertEquals("Art piece name cannot be empty.", error);
	}

	/**
	 * Test to create an art piece with a malformed artist email. Should be rejected
	 * by
	 * the email format check before any repository lookup happens.
	 */
	@Test
	public void testCreateArtPieceInvalidArtistEmailFormat() {
		String error = null;
		ArtPiece artPiece = null;
		try {
			artPiece = service.createArtPiece("Riverside Tree", 3, 800f, 10, 23f, "tree on a riverside",
					"not-an-email");
		} catch (IllegalArgumentException e) {
			error = e.getMessage();
		}
		assertNull(artPiece);
		assertEquals("Artist email is not a validly formatted email address: not-an-email", error);
	}

	/**
	 * Test to create an art piece referencing an artist email that is validly
	 * formatted
	 * but does not correspond to any real artist. Regression test for the bug where
	 * the
	 * art piece was silently created with a null artist instead of being rejected.
	 */
	@Test
	public void testCreateArtPieceArtistNotFound() {
		String error = null;
		ArtPiece artPiece = null;
		String unknownButValidEmail = "nobody@mail.com";
		try {
			artPiece = service.createArtPiece("Riverside Tree", 3, 800f, 10, 23f, "tree on a riverside",
					unknownButValidEmail);
		} catch (ResourceNotFoundException e) {
			error = e.getMessage();
		}
		assertNull(artPiece);
		assertEquals("No artist found with email: " + unknownButValidEmail, error);
	}

	/**
	 * Test that leading/trailing whitespace on name/description/email fields is
	 * trimmed
	 * rather than stored as-is.
	 */
	@Test
	public void testCreateArtPieceTrimsWhitespace() {
		ArtPiece artPiece = null;
		try {
			artPiece = service.createArtPiece("  Riverside Tree  ", 3, 800f, 10, 23f, "  tree on a riverside  ",
					"  " + VALID_ARTIST_EMAIL + "  ");
		} catch (IllegalArgumentException e) {
			fail();
		}
		assertNotNull(artPiece);
		assertEquals("Riverside Tree", artPiece.getArtName());
		assertEquals("tree on a riverside", artPiece.getDescription());
		assertEquals(VALID_ARTIST_EMAIL, artPiece.getArtist().getEmail());
	}
}