
services:
  gallery-postgres:
    container_name: gallery-postgres
    image: postgres:16
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: gallerydb

    ports:
      - "5432:5432"

    volumes:
      - gallery_postgres_data:/var/lib/postgresql/data

  gallery-backend:
    container_name: gallery-backend
    image: art-gallery-backend
    restart: unless-stopped

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://gallery-postgres:5432/gallerydb
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

    ports:
      - "8080:8080"

    depends_on:
      - gallery-postgres

volumes:
  gallery_postgres_data:

